export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const WORK_REPOSITORY = 'WORK_REPOSITORY';
export const INSPECTIONPLAN_REPOSITORY='INSPECTIONPLAN_REPOSITORY'
export const CUSTOMER_REPOSITORY='CUSTOMER_REPOSITORY'
export const VENDOR_REPOSITORY='VENDOR_REPOSITORY'
export const LOCATION_REPOSITORY='LOCATION_REPOSITORY'
export const DESCRIPTIONCONTROL_REPOSITORY='DESCRIPTIONCONTROL_REPOSITORY'
export const WORKSTEPS_REPOSITORY = 'WORKSTEPS_REPOSITORY';
export const WORKPRODUCTS_REPOSITORY = 'WORKPRODUCTS_REPOSITORY';
export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY';
export const CERTIFICATE_REPOSITORY='CERTIFICATE_REPOSITORY'

